### ISSUE TITLE
Problem with Chinese text ISO Standard

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#115]
@opoudjis I've encountered this really strange bug.

If I have these lines in the T&D section, the entire section 3 doesn't render. This is simply the translation of the ISO boilerplate.

In addition, the links can't get rendered even in the English version.

```
* ISO在线浏览平台： http://www.iso.org/obp
* IEC Electropedia： http://www.electropedia.org
```

Thanks!

**Comment by opoudjis** [comment]
The English version links are now working. The boilerplate is supplied by Isodoc; any boilerplate in the source is in fact meant to be ignored.

**Comment by ronaldtse** [comment]
But we still need a way to override the boilerplate text for the translation of the boilerplate text. For the foreword, just in case, the bottom part often describes the history of the edition and will be different for most documents (and hence is not boilerplate text)

**Comment by opoudjis** [comment]
Right, and for that reason I don't introduce any boilerplate into the foreword: it's just too variable. 

The boilerplate is only in Normative References and Terms and Definitions, and it needs to be there, because it is determined by the contents (and the user shouldn't have to do that check).

https://github.com/riboseinc/isodoc/issues/47 is going to introduce Chinese text for that terms & definitions boilerplate. I don't agree that the boilerplate text should be overridden for translation by the user: it should be overridden by the gem, which should know the boilerplate in the target language.

**Comment by ronaldtse** [comment]
Isn't it hard for the gem to know the boilerplate in "all" the target languages? This means we need to have a pre-set list that we support.

**Comment by opoudjis** [comment]
And I'm OK with that. The i18n module is all in one file, and it's a finite set, realistically.

**Comment by opoudjis** [comment]
As I said in message, we can deal with unsupported languages by asking users to provide the localisations as document attributes (or maybe a yaml prefix), once we've got the full list of localisations done.

**Comment by opoudjis** [comment]
Is this issue still there?

**Comment by ronaldtse** [comment]
@opoudjis I agree that we should allow unsupported languages with a YAML file (or a prefix). The key point is to provide them with a sample template (e.g., via a command like `asciidoctor-iso generate-language-template`) (a list of keys they need to fill).

**Comment by opoudjis** [comment]
There's a template already provided, and linked from the README. As of now, all i18n (including English) is done by YAML.

**Comment by opoudjis** [comment]
As far as I can tell, this issue has gone away.
