### ISSUE TITLE
README doesn't tell you what [.source] does in T&D (and unable to reference clause now)

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#139]
There are two usages of [.source] in T&D:

1. indicate the term being imported from a source.
```
[.source]
<<ISO1001,clause 1.1>>
```

This is not working -- it only shows the document identifier without the clause number.

It is also not shown in the README, but is shown in Rice doc.

2. indicate the term has been modified from a source.

```
[.source]
<<ISO1001>>, 1.1, this is why it got changed...
```

This one works but not described.

**Comment by opoudjis** [comment]
This is a bug: I thought manipulating node.dup and stripping it of localities was leaving the original unaffected, but it isn't.

**Comment by opoudjis** [comment]
https://github.com/sparklemotion/nokogiri/issues/1678

What a tool.

**Comment by opoudjis** [comment]
Of the two alternatives presented, the former is the desired one, with the locality incorporated into the reference. It wasn't picked up in unit testing, because the locality was being stripped erroneously downstream. 

(I was stripping localities for style validation from a clone of the node, but so long as the cloned node is in the same document, stripped elements from the clone  strips them from the original! Somehow, that's supposed to be expected behaviour of Ruby enumerables, and nokogiri's maintainer is unrepentant.)

Bug fixed. The latter alternative works, but is not desirable, because it's not a true citation—we should be treating all citation localities the same.
