### ISSUE TITLE
Citations showing as just "[ref], [locality]"

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#147]
Currently a cross reference like:

```
[[[iso8601,ISO 8601]]], _Data elements and interchange formats -- Information interchange -- Representation of dates and times_

See this 1: <<ISO8601,clause 1.2.3>>!
See this 2: <<ISO8601,section 2.3>>!

```

Is rendered as:
```
See this 1: ISO 8601, 1.2.3!
See this 2: ISO 8601, 2.3!
```

This rendering loses the locality specifier ('clause', 'section') and also gives no hint to the user what that exactly meant.

Can we have something like `ISO 8601, Clause 1.2.3` instead?

**Comment by opoudjis** [comment]
No.

The omission of "clause" in ISO references where the locality has a subclause is explicitly prescribed in ISO/IEC DIR 2. "ISO 8601, 1.2.3" is exactly how ISO expects such references to be cited. (OTOH, if the clause has no subclause, "clause" is preserved: "ISO 8601, clause 5." 

I've done the same for "section" by analogy, since sections are used for ISO references on occasion instead of "clause". This convention does not apply to other locality types.
