### ISSUE TITLE
Allow "comment" type block for review comments

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#15]
Comments relevant for the review of a document are often placed inline to the document but in some red text after the text item. These are useful comments to the reviewing reader but are not intended to be published. These comments are currently inserted in Word using various color options (blue, red...)

We should allow the existence of these comments (in some special tag), and only render them if it is under "draft" or "with-comments" mode.

**Comment by opoudjis** [comment]
These are going to have to be sidebars in Asciidoc; Admonitions are taken, and the renderer ignores comments.

**Comment by opoudjis** [comment]
These are going to have to be asides; admonitions are already being used for notes, and Asciidoc comments are ignored by the renderer.

**Comment by opoudjis** [comment]
Are the colours significant? Do they need to be tagged?

**Comment by ronaldtse** [comment]
I think we should not allow defining color tags but allow differentiating comments by time / authors.. I've seen documents with two or three colors, used to indicate when the comments originated from (e.g., first review, second review, etc.)

But there are many types of admonitions, right? And ISO documents only have "Note"?

**Comment by opoudjis** [comment]
No, ISO have several types of admonition, and in fact we won't have enough in Asciidoc to cover them: 

ISO: Danger, Caution, Warning, Important, Safety Precautions. 
Asciidoctor: NOTE, TIP, IMPORTANT, CAUTION, WARNING

We would have to map NOTE and TIP to Danger and Safety Precautions, or else make Danger and Safety Precautions subcases of Warning. I could use NOTE instead of Aside, but I'd rather treat all warnings as the one thing.

**Comment by ronaldtse** [comment]
Ah ha, instead of a "mapping" could we define our own admonition blocks in Asciidoctor? e.g., `danger`

**Comment by opoudjis** [comment]
Unfortunately no, we cannot: the admonition types are fixed. We can add them as types of open block, but I think I'd rather treat them all syntactically the same, so:

[type = "danger"]
CAUTION: Caution caution

Note for content clarification is already implemented --- NOTE. So I'm using admonitions for both notes and warnings.

**Comment by ronaldtse** [comment]
Apparently it is possible to create a custom admonition type:

https://github.com/asciidoctor/asciidoctor-extensions-lab/issues/9

Perhaps we can use this instead of "mapping" -- since "mapping" really requires the author to remember what maps to what?

**Comment by opoudjis** [comment]
I have implemented this as a sidebar:

````
[source=ReviewerName,date=20000101]
****
Reviewer's comment
****
````

(The date is not yet in the document model)

Sidebars are no better or worse than admonitions. Both are blocks rather than inline, and I could implement these as custom inline formatting instead; but I like the fact that sidebars will render into any postprocessing of Asciidoc. 

Are you OK with that, or do you want inline? As it stands, all sidebars that are children of  a clause are tucked into the end of their preceding element, so it doesn't look that bad.

**Comment by ronaldtse** [comment]
@opoudjis I am really looking forward to the day we can directly generate PDFs without Word, given that the output is already styled in HTML. 

Sidebar is perfect. I've added a new `ReviewBlock` for this.
