### ISSUE TITLE
Cache isobib retrievals

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-iso#155]
Global cache + local cache

**Comment by ronaldtse** [comment]
Something like:

* Global cache: `[home]/.relaton-bib/*.{xml,json}`
* Local cache: `[document directory/relaton/bibliography/*.{xml,json}`

**Comment by opoudjis** [comment]
... I'm not clear why we need a local cache, if every fetched item automatically goes to global cache anyway. Could you explain your thinking here?

This will be key/value; but I can put the XML serialisation as a JSON value.

**Comment by ronaldtse** [comment]
Local cache: we want it because we sometimes want the full state in the document repository. For example, if I just cloned a repo and go offline, I can still build the document correctly. At least this should be an option -- this is the method I will personally use.

**Comment by opoudjis** [comment]
So dump everything that's going to go into the global cache for a doc into a local cache as well? And if I find a global cache, and a local cache, do I check in both?

Global cache is working now.

**Comment by ronaldtse** [comment]
Dump everything: Yes please for the local cache, for that doc only. 

Do I check in both? Yes, check both caches.

Global cache should always be populated directly from the authoritative site. Local cache receives entries from Global cache and can also be manually edited.

* If we have it in global (and it is not stale) not local, copy it to local. Use the global entry (identical to local).
* If we have it in local cache, but not in global, global should fetch it (if there is no Internet, skip the global cache fetch). Use the local entry.
* If we don't have in either, fetch global and fill into local.
* If a global cache entry is stale, it needs to be refetched.
* If a local cache entry is sourced from Global, and stale, it should be updated with the Global one. If a local cache entry is not from Global (maybe that guy made it up), it should not be updated.

Local bib storage should only enabled via an option. For example, `metanorma --bib-dir relaton-bib [...]`. Otherwise there is only global cache.

**Comment by opoudjis** [comment]
For asciidoctor-iso cli, triggering local cache with document attribute `:local-cache:`.

**Comment by opoudjis** [comment]
I've implemented the rules, but I don't have any way of telling whether a reference is stale or not; and the ISO references are slow-moving enough that I don't think I need to. Staleness is really about detecting a more recent reference than what is already there; given the mess of isobib years currently, I'd like to defer implementing that, and treat it as an enhancement, preferably doing it only if the global cache hasn't been updated in a while. https://github.com/riboseinc/asciidoctor-iso/issues/156
