### ISSUE TITLE
Unable to add a list within a NOTE entry

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#165]
Unable to add a list within a NOTE entry. This snippet is supposed to have a list in the note.

```adoc
== Terms and definitions

=== time scale
blah

NOTE: A time scale may amongst others be chosen as:
+
--
* item
* item
--
```

**Comment by ronaldtse** [comment]
From @opoudjis : make note a delimited block

https://asciidoctor.org/docs/user-manual/#admonition

```adoc
[NOTE]
.Feeding the Werewolves
====
While werewolves are hardy community members, keep in mind the following dietary concerns:

. They are allergic to cinnamon.
. More than two glasses of orange juice in 24 hours makes them howl in harmony with alarms and sirens.
. Celery makes them sad.
====
```

Closing.

**Comment by ronaldtse** [comment]
@opoudjis could you help add this to the Authoring Guide? Thanks!

**Comment by opoudjis** [comment]
I could, but I don't think I should. The Authoring Guide is much too big as is. It should not also be a primer on how to write generic Asciidoctor (which is what multi-paragraph notes are): it will end up replicating much of the Asciidoctor User Manual if it does. (Especially because these are niche areas of Asciidoctor syntax.) The real solution is what I've already done: ask people to get familiar with the Asciidoctor User Manual first, then consult the Authoring Guide for AsciiISO enhancements (and refer back to the User Manual for more general queries.)

**Comment by ronaldtse** [comment]
Well, I still think that features that people will use a lot with ISO documents should go into the Authoring Guide. We can easily point them to the correct paragraph in the Asciidoctor Manual.

* multi-paragraph notes / examples
* `{blank}` lines for titles
* substitute text for xrefs
* document attributes

These should really warrant some mention in our Authoring Guide...

**Comment by opoudjis** [comment]
Added two of these to Guide as tips, and the other two inline in the Guide.
