### ISSUE TITLE
External reference bug on display of <<REF,x.x.x>>

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#168]
```adoc
== Terms and definitions
=== foo
foobar

NOTE: Also see <<ISO80000-3,Annex C 3-7>>.

NOTE: Also see <<ISO80000-3,3-7>>.

[bibliography]
== Bibliography
* [[[ISO80000-3,ISO 80000-3]]], _Quantities and units -- Part 3: Space and time_
```

The first one will be rendered as:
```
Note 1 to entry: Also see ISO 80000-3, Annex C 3–7.
```

The second one is rendered as:
```
Note 2 to entry: Also see 3–7.
```

**Comment by opoudjis** [comment]
Yes, and that is correct behaviour.

`<<a,b>>` in Asciidoctor is crossreference, followed by replacement text. The canonical rendering of `<<a,b>>` is `<a href="#a">b</a>`.

Localities suffix the locality to the reference, instead of replacing it. The introduction of localities is something AsciiISO does, and it is conditional on an explicit locality prefix: that is how they are recognised. `<<ISO80000-3,Annex C 3-7>>` is recognised as a locality reference because "annex" is there.  `<<ISO80000-3,The previous reference>>` is treated as a normal crossreference with replacement text.

We can make the processing more flexible, or we can emphasise (which the documentation already does) that all localities must be explicit. As you can guess, I prefer the latter.

And remember (again): ISO leaves out "clause" in its rendering of ISO references, but IsoXML does not, and nor should the user. Localities must be explicit. The correct encoding of what will be rendered as "ISO 80000-3, 3-7" is `<<ISO80000-3,clause 3-7>>`, parsed as `<eref target="iso80000-3"><locality type="clause">3-7</locality></eref>`.

**Comment by ronaldtse** [comment]
I have to say that this is rather idiosyncratic syntax as “locality” is mixed up with “replacement text".

Can we separate these syntaxes fully, such as `<<ISO80000-3,clause=3.7>>` for setting locality?

**Comment by opoudjis** [comment]
That would be a breaking change, but:

The current syntax is `<<ref,(locality value,)*replacement_text*>>`; e.g. `<<ref,clause 3.4,note 1>>`, `<<ref,clause 3.4,note 1,the final note>>`

You want that to become `<<ref,(locality=value,)*replacement_text*>>`?

**Comment by ronaldtse** [comment]
@opoudjis I would prefer a declarative syntax than an inferring one. Just like how Asciidoctor uses the table syntax `[cols="a,2a",options="header"]`, we can have `<<ref,clause=3.4,note=1,the final note>>`?

We can still accept the existing syntax, but just an additional declarative one. Thoughts?
