### ISSUE TITLE
Bibliography should treat numbering and titles as separate columns (or starting at different tabs)

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#31]
In the Bibliography section:

* all referred items should have a reference number
* all reference numbers (`[1] xxx` `[2] xxx`) should be aligned at left
* all titles should be aligned at left

**Comment by opoudjis** [comment]
Right. There's a more general issue here:

ISO and IEC references in the bibliography are referenced in the body not by reference numbers, but by their normal ISO number; for example, in the Rice document,  _Water for analytical laboratory use -- Specification and test methods_ is reference [1], but is referenced as ISO 3696.

I need to keep the bibliographic reference as 

````
* [[[ISO3696,ISO 3696]]], _Water for analytical laboratory use -- Specification and test methods_
````

for that reason, the "ISO 3696" is an instruction for the rest of the document. In the context of the *bibliography*, the ISO reference will be overridden by an ordinal number; but users will then need to remember to list ISO references before non-ISO references, so that the ordinal number is correct.

**Comment by ronaldtse** [comment]
@opoudjis Exactly -- this is needed separation of the citation rendering (reference number or document reference) and the bibliography entry numbers.

I'm not sure if we should close this though because in the Rice PDF all ISO/IEC references have their "reference number" correct.

It actually got me wondering if we should implement the auto-fetch of ISO/IEC document metadata like RFCs. Let's discuss this in a separate issue.

**Comment by opoudjis** [comment]
I now give the correct reference numbers in the bibliography (assuming they are correctly ordered, with ISO before non-iso references); is there anything else that needs to be done?
