### ISSUE TITLE
ISO table border formatting

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#36]
I think this applies to HTML/PDF as well as Word.

1. Outer table border should have double width
2. Header table row bottom border should have double width
3. Header table row text should be bolded

**Comment by opoudjis** [comment]
Outer table border double width: not the case for the ISO document template. Could you confirm?

**Comment by opoudjis** [comment]
Confirmed, Word wasn't showing it clearly

**Comment by opoudjis** [comment]
1.5 hrs over.

I've *kinda* done this, but there is a rendering issue: Asciidoc only allows 1 footer and 1 header row, and ISO clearly allows more in the rice document (since the headers can be broken down into subcells). I will need to add to the document model a count of header rows and header columns, and use that as the criterion for where the header and footer start and end.

**Comment by opoudjis** [comment]
This ticket is subsumed into #24.

**Comment by opoudjis** [comment]
Almost working
