### ISSUE TITLE
Update operations according to IsoDoc model generalization

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#62]
Relevant commit https://github.com/riboseinc/isodoc-models/commit/3f8c0b3fe52f5ac9821582750e359fbbf7b75bb7

Now there are three types of documents:

* BasicDocument: contains BibItem and sections
* StandardDocument: contains BibItem, sections, appendix, references
* IsoStandardDocument: contains customized models and overrides

**Comment by opoudjis** [comment]
The impact of this is to refactor the asciidoctor-iso gem into two classes (maybe three), with one inheriting from the next, and for isodoc similarly to be refactored. I'm reluctant to make them separate gems; that's just getting too confusing.

**Comment by opoudjis** [comment]
Iso specific stuff should move to asciidoctor-iso child of isodoc (which renames to stddoc).

We'll keep basicdocument + standarddocument in this gem.

**Comment by opoudjis** [comment]
Oh god.

Mercifully the isodoc gem already has an isodoc::iso subclass, so refactoring that won't be as hard: it's just a matter of moving more ISO-specific content to the subclass, and maybe renaming the modules. (Maybe not.) I'm making the isodoc refactoring a separate ticket, but in fact there's not much to do there.

Consistent with #194, the new gem will be called Metanorma-Stddoc.

Asciidoctor-ISO gets refactored to look like all the other Asciidoctor-* gems, inheriting from Asciidoctor-Stddoc. The bulk of Asciidoctor-ISO content migrates to Metanorma-Stddoc.

Asciidoctor-ISO–specific content is:

* bibdata
* preface as foreword + introduction; stddoc has just a preface
* annex and appendixes; stddoc has just annexes
* termsources element
* almost all validation

Changes in enums do not matter for the split, because they are a matter of validation, not coding.

ISO Bibliographic Item is not in scope of this split, since Bibliographic Item modelling is decoupled from standards modelling (ISO references can occur elsewhere.)

**Comment by ronaldtse** [comment]
The phrase “stddoc” sounds too much like “std” which isn’t that great. I’m sure he linguist in you can find something more appropriate :wink:

**Comment by opoudjis** [comment]
StandardDoc.

**Comment by opoudjis** [comment]
metanorma-standoc created, and asciidoctor-iso inherits from it. rspec passed for asciidoctor-iso. rspec of metanorma-standoc does not pass, but the fix for that is now doing to be in https://github.com/riboseinc/isodoc/issues/63.
