### ISSUE TITLE
Issues with {technical , sub}committee and workgroup types

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-iso#77]
1. JTC and SC are valid types for technical committee types and subcommittee types respectively. However, validation output says:

```
ISO: invalid technical committee type JTC
ISO: invalid subcommittee type SC
```

2. When `subcommittee-type` and `workgroup-type` are not set, the defaults are not shown when being used inside text like `{subcommittee-type}` will just show up verbatim as text.

**Comment by opoudjis** [comment]
1. Fixed.

2. We clearly need to coordinate on template text (https://github.com/riboseinc/isodoc/issues/5, https://github.com/riboseinc/isodoc/issues/6). I am not exposing XML elements atomically, but in combination: the templating function populate_template() in isodoc (and inheritors) does not deal with {subcommittee-type} but inserts it directly into TCNUM, SCNUM, WGNUM, because the type never appears in isolation from the number. And I don't think that's wrong.

So the template is being populated with the type correctly now; the default value is assigned within isodoc ():

````
    def sc(xml)
      sc_num = xml.at(ns("//isoworkgroup/subcommittee/@number"))
      sc_type = xml.at(ns("//isoworkgroup/subcommittee/@type"))&.text || "SC"
      set_metadata(:sc, "XXXX")
      set_metadata(:sc, "#{sc_type} #{sc_num.text}") if sc_num
    end
````

... Can I close this?

**Comment by ronaldtse** [comment]
Re item 2 I was using the Rice model template convention since the beginning, so it was kind of an inherited problem. Perhaps we can work on this directly with template text.

The thing is, while the Foreword section can be mostly templated, different documents still use very different content. So it would be much more appropriate to "manually template" them.

**Comment by opoudjis** [comment]
I think I got confused, you are referring to substitution of Asciidoc Document attributes, right?

**Comment by opoudjis** [comment]
... no, I don't understand what to do here. @ronaldtse , please explain?

**Comment by ronaldtse** [comment]
Indeed I was referring to substitution of AsciiDoc document attributes, specifically in the Foreword section that explains where the work originated from, that shows TC/SC/WG etc.

**Comment by opoudjis** [comment]
2... Yes, and if you don't set the document attribute `:subcommittee-type:`, then you can't expect the `{subcommittee-type}` text to be populated: that is explicitly populated by Asciidoc out of the document header. 

We don't have to use those  `{subcommittee-type}` at all, but I do envision authoring to work by copy-pasting things into the Rice document as a template. I can take the `{subcommittee-type}`  out of the document if you like, but I think this is simply a matter of explanation in the Readme.
